# Generated by Django 5.2.5 on 2025-10-08 08:57

import commentaires.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.CharField(default=commentaires.models.custom_commentaire_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('contenue', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_jaime', models.IntegerField(default=0)),
                ('id_commentaire_parent', models.ForeignKey(blank=True, db_column='id_commentaire_parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaires.commentaire')),
                ('id_projet', models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='projets.projet')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commentaire',
            },
        ),
    ]
