# Generated by Django 5.2.5 on 2025-10-08 08:57

import django.db.models.deletion
import realisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id_realisation', models.CharField(default=realisations.models.custom_realisation_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('contenue', models.CharField(blank=True, max_length=255, null=True)),
                ('valeur_realise', models.IntegerField(default=0)),
                ('debut_realisation', models.DateField(blank=True, null=True)),
                ('fin_realisation', models.DateField(blank=True, null=True)),
                ('ecart_realisation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_rapport', models.ForeignKey(db_column='id_rapport', on_delete=django.db.models.deletion.CASCADE, to='rapports.rapport')),
            ],
            options={
                'db_table': 'realisation',
            },
        ),
    ]
