# Generated by Django 5.2.5 on 2025-10-13 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
