# Generated by Django 5.2.5 on 2025-10-08 08:57

import entites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id_entite', models.CharField(default=entites.models.custom_entite_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('abreviation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'entite',
            },
        ),
    ]
