# Generated by Django 5.2.5 on 2025-10-08 08:57

import django.db.models.deletion
import objectifs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('axes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id_objectif', models.CharField(default=objectifs.models.generate_objectif_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('id_axe', models.ForeignKey(db_column='id_axe', on_delete=django.db.models.deletion.CASCADE, to='axes.axe')),
            ],
            options={
                'db_table': 'objectif',
            },
        ),
    ]
