# Generated by Django 5.2.5 on 2025-10-08 06:55

import django.db.models.deletion
import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_utilisateur', models.CharField(default=utilisateurs.models.custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_region', models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
