# Generated by Django 5.2.5 on 2025-10-08 08:57

import axes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id_axe', models.CharField(default=axes.models.generate_axe_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'axe',
            },
        ),
    ]
