# Generated by Django 5.2.5 on 2025-10-08 06:55

import regions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(default=regions.models.generate_region_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postale', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
    ]
