# Generated by Django 5.2.5 on 2025-10-08 08:57

import django.db.models.deletion
import rapports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_rapport', models.CharField(default=rapports.models.custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('periodicite', models.CharField(blank=True, choices=[('Hebdomadaire', 'Hebdomadaire'), ('Mensuelle', 'Mensuelle'), ('Trimestrielle', 'Trimestrielle'), ('Semestrielle', 'Semestrielle'), ('Annuelle', 'Annuelle')], max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('solution', models.CharField(blank=True, max_length=255, null=True)),
                ('probleme', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_projet', models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='projets.projet')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport',
            },
        ),
    ]
