# Generated by Django 5.2.5 on 2025-10-12 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
