# Generated by Django 5.2.5 on 2025-10-08 08:57

import django.core.validators
import django.db.models.deletion
import projets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objectifs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.CharField(default=projets.models.cusstomId, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('indicateur', models.CharField(blank=True, max_length=255, null=True)),
                ('unite_indicateur', models.CharField(blank=True, max_length=255, null=True)),
                ('valeur_cible', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_estimatif', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('impact_socio_eco', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('id_objectif', models.ForeignKey(db_column='id_objectif', on_delete=django.db.models.deletion.CASCADE, to='objectifs.objectif')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projet',
            },
        ),
    ]
