# Generated by Django 5.2.5 on 2025-10-12 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
