# Generated by Django 5.2.5 on 2025-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_alter_projet_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
