# Generated by Django 5.2.5 on 2025-10-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entites', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entite', models.ForeignKey(db_column='id_entite', on_delete=django.db.models.deletion.CASCADE, to='entites.entite')),
                ('id_projet', models.ForeignKey(db_column='id_projet', on_delete=django.db.models.deletion.CASCADE, to='projets.projet')),
            ],
            options={
                'db_table': 'entite_projet',
            },
        ),
    ]
