# Generated by Django 5.2.5 on 2025-10-19 10:02

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.CharField(default=notifications.models.generate_notification_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('commentaire', 'Commentaire'), ('axe', 'Axe'), ('objectif', 'Objectif'), ('projet', 'Projet'), ('rapport', 'Rapport'), ('alerte', 'Alerte')], max_length=100)),
                ('id_cible', models.CharField(blank=True, max_length=20, null=True)),
                ('role_cible', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
